### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by mamigot** [iblai/quickstarts#1]
**Start each document by defining whether it’s a superuser endpoint (requiring system level oauth2 creds) or a tenant admin endpoint (requiring tenant token… use this instead of per user creds)**

catalog.py — how to create a course, program, pathway or resource — @gipsbrian 

user.py — how to create a user — @gipsbrian 

tenant.py — how to create a tenant and associate it with a user @gipsbrian 

enrollment.py — how to enroll a user into a course or program — @gipsbrian 

credential.py — how to create and issue a credential for a course — @gipsbrian 

skill.py — how to create and associate skills with courses as well as with users (desired) — @gipsbrian 

role.py — how to associate roles with users — @gipsbrian 

index.py — how to create an index for mentors to interact with (rag) — @ojaragodwin 

mentor.py — to create a mentor associated with an index (rag) — @ojaragodwin 

chat.py — how to chat with a mentor (sync and async) — @ojaragodwin 

bot.py — how to create a bot associated with a mentor — @Joetib

**Comment by gipsbrian** [comment]
[ibl-demo-api-scripts.zip](https://github.com/user-attachments/files/16288303/ibl-demo-api-scripts.zip)

# ibl demo api call scripts

## user.py
- user creation call

## catalog.py
- course creation
- program creation
- pathway creation
- resource creation

## tenant.py
- Tenant launch

## enrollment.py
- enrol user call
- bulk enrol user to courses
- bulk enrol student into a course

## credential.py
- get issuer from org
- create credential
- issue credential

## skills.py
- create or update skills
- create or update desired skills
- create or update reported skills

## role.py
- create or update role
- create or update desired role
- create or update reported role
